### ISSUE TITLE
Prepare for deployment on NW ABAP

### ISSUE THREAD

**Issue by ghost** [saschakiefer/generator-openui5#86]
Hi! 
I have used the generator-openui5 with sucess, and now i want to deploy my new project to the ABAP server. 

How to you guys do that? 

As far as i can se - i have to manually correct the UI5 refrence from the header, and then create a folderstructure that i can upload using the  /UI5/UI5_REPOSITORY_LOAD report in ABAP. 

Is this how you do it to - or is there a smarter way to make the application "deployment ready"? 

Best regards 
Ronni

**Comment by js1972** [comment]
You are correct... for the time-being... I'm working on the build script such that the UI5 library location won't have to be changed soon but you'll still need to manually load it as a BSP with `/UI5/UI5_REPOSITORY_LOAD`.

**Comment by ghost** [comment]
Hi Jason! 
Thanks for your reply - thats great news!  And thanks for sharing your thoughts regarding the dynamic report still in play. 

I guess i will have to manually upload the content - for the time being - and change the UI5 refrence manually before uploading. 

I am looking forward to the solution improvments :+1: 

have a nice day. 
br 
Ronni
