### ISSUE TITLE
Unable to run Grunt Serve

### ISSUE THREAD

**Issue by gentiger** [saschakiefer/generator-openui5#87]
Hi all,

This is my first time trying out the generator (and Yeoman) and I have follow all the instruction to generate the file. However I am unable to start the local server with the following error:

![yeoman-ui5-grunt-serve-error](https://cloud.githubusercontent.com/assets/9399857/7406099/bfb49028-ef2f-11e4-858f-f7e2fa68a4e8.PNG)

Can anyone guide me how to get it run correctly?

**Comment by js1972** [comment]
I haven't seen that before... Just checking but have you done an `npm install` first..?
Also - check this out: https://github.com/drewzboto/grunt-connect-proxy/issues/97

**Comment by gentiger** [comment]
I am able to run it now. Had update the dependencies version to ~1.11.0 and execute `npm install`
